### ISSUE TITLE
I can't install models

### ISSUE THREAD

**Issue by hubrockman** [ForserX/StableDiffusionUI#28]
How can I import the normal models that are downloaded from any site?
When I try to do it, it rejects me

Startup extract ckpt(D:\SD\stable-diffusion-webui\models\Stable-diffusion\abyssorangemix3AOM3_aom3a1.safetensors)..... 

Microsoft Windows [Version 10.0.19045.3208]
(c) Microsoft Corporation. Todos los derechos reservados.
global_step key not found in model
Traceback (most recent call last):
  File "${Workspace}\repo\diffusion_scripts\convert\convert_original_stable_diffusion_to_diffusers.py", line 103, in <module>
    pipe = download_from_original_stable_diffusion_ckpt(
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1291, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(checkpoint)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 737, in convert_ldm_clip_checkpoint
    text_model.load_state_dict(text_model_dict)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
	Unexpected key(s) in state_dict: "text_model.embeddings.position_ids". 
${Workspace}\repo>"onnx.venv/Scripts/python.exe" "./diffusion_scripts/convert/convert_diffusers_to_onnx.py" --model_path="D:/SDTEST/XUI.3.3.Preview/models/diffusers/abyssorangemix3AOM3_aom3a1" --output_path="${Workspace}\models\onnx/abyssorangemix3AOM3_aom3a1"
${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\models\cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
  deprecate(
${Workspace}\models\onnx/abyssorangemix3AOM3_aom3a1
Traceback (most recent call last):
  File "${Workspace}\repo\diffusion_scripts\convert\convert_diffusers_to_onnx.py", line 366, in <module>
    convert_models(args.model_path, args.output_path, args.opset, args.fp16)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "${Workspace}\repo\diffusion_scripts\convert\convert_diffusers_to_onnx.py", line 80, in convert_models
    pipeline = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=dtype).to(device)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 903, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\configuration_utils.py", line 350, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory D:/SDTEST/XUI.3.3.Preview/models/diffusers/abyssorangemix3AOM3_aom3a1.
${Workspace}\repo>exit

**Comment by ForserX** [comment]
> RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
Check the input data and the model version

If my memory does not change, then such departures are typical when you shove 2.0 into SD 1.5

**Comment by hubrockman** [comment]
> 

Thanks for answering, what kind of measures should I take from here? I'm sorry I'm not so knowledgeable on the subject, I barely know how to install some things using python commands and little else
