### ISSUE TITLE
Getting errors when trying to run models

### ISSUE THREAD

**Issue by Aphex123** [ForserX/StableDiffusionUI#4]
Im getting errors whenever i try to run a model using ONNX on a 6700xt. I dont get this error when i run using CPU

`Traceback (most recent call last):
  File "${Workspace}\repo\diffusion_scripts\sd_onnx_safe.py", line 28, in <module>
    pipe = GetPipe(opt.mdlpath, opt.mode, True, opt.nsfw, False)
  File "${Workspace}\repo\diffusion_scripts\sd_xbackend.py", line 57, in GetPipe
    pipe = OnnxStableDiffusionPipeline.from_pretrained(Model, custom_pipeline="lpw_stable_diffusion_onnx", provider=prov, safety_checker=nsfw_pipe)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 706, in from_pretrained
    config_dict = cls.load_config(cached_folder)
  File "${Workspace}\repo\onnx.venv\lib\site-packages\diffusers\configuration_utils.py", line 320, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory ${Workspace}\models\onnx/deliberate_v2.`

**Comment by ForserX** [comment]
\models\onnx/deliberate_v2:
![image](https://user-images.githubusercontent.com/13867290/229705920-eb8bb07a-cb10-4b80-bf75-3771678fb777.png)

It should look like this. 

Can you describe in more detail how you carried out the import?

**Comment by ForserX** [comment]
Check 3.1.1. 
https://github.com/ForserX/StableDiffusionUI/releases/tag/3.1.1
